version: "3.9"
services:
  # Replica shard Nr1
  mongoRS1n1:
    image: mongo
    container_name: mongoRS1n1
    # Terminal emulator: xterm
    environment:
      - TERM=xterm
    # ?
    ports:
      - "27017:27017"
    # ?
    expose:
      - "27017"
    # ?
    command: mongod --shardsvr --replSet mongoRS1 --dbpath /data/db --port 27017
    # ?
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./database/data1:/data/db

  # Replica shard Nr2
  mongoRS1n2:
    image: mongo
    container_name: mongoRS1n2
    # Terminal emulator: xterm
    environment:
      - TERM=xterm
    # ?
    ports:
      - "27027:27017"
    # ?
    expose:
      - "27017"
    # ?
    command: mongod --shardsvr --replSet mongoRS1 --dbpath /data/db --port 27017
    # ?
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./database/data2:/data/db

  # Replica shard Nr3
  mongoRS1n3:
    image: mongo
    container_name: mongoRS1n3
    # Terminal emulator: xterm
    environment:
      - TERM=xterm
    # ?
    ports:
      - "27037:27017"
    # ?
    expose:
      - "27017"
    # ?
    command: mongod --shardsvr --replSet mongoRS1 --dbpath /data/db --port 27017
    # ?
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./database/data3:/data/db

  # Config Server 1
  mongoCFG1:
    image: mongo
    container_name: mongoCFG1
    # Terminal emulator: xterm
    environment:
      - TERM=xterm
    # ?
    expose:
      - "27017"
    # ?
    command: mongod --configsvr --replSet mongoRS1conf --dbpath /data/db --port 27017
    # ?
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./mongo_cluster/config1:/data/db

  # Config Server 2
  mongoCFG2:
    image: mongo
    container_name: mongoCFG2
    # Terminal emulator: xterm
    environment:
      - TERM=xterm
    # ?
    expose:
      - "27017"
    # ?
    command: mongod --configsvr --replSet mongoRS1conf --dbpath /data/db --port 27017
    # ?
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./mongo_cluster/config2:/data/db

  # Config Server 3
  mongoCFG3:
    image: mongo
    container_name: mongoCFG3
    # Terminal emulator: xterm
    environment:
      - TERM=xterm
    # ?
    expose:
      - "27017"
    # ?
    command: mongod --configsvr --replSet mongoRS1conf --dbpath /data/db --port 27017
    # ?
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./mongo_cluster/config3:/data/db

  # Router Instance 1
  mongoS1:
    image: mongo
    container_name: mongoS1
    # ?
    depends_on: 
      - mongoCFG1
      - mongoCFG2
    # ?
    command: mongos --configdb mongoRS1conf/mongoCFG1:27017,mongoCFG2:27017,mongoCFG3:27017 --port 27017
    # ?
    ports:
      - "27019:27017"
    # ?
    expose:
      - "27017"
    # ?
    volumes:
      - /etc/localtime:/etc/localtime:ro

  # Router Instance 2
  mongoS2:
    image: mongo
    container_name: mongoS2
    # ?
    depends_on: 
      - mongoCFG1
      - mongoCFG2
    # ?
    command: mongos --configdb mongoRS1conf/mongoCFG1:27017,mongoCFG2:27017,mongoCFG3:27017 --port 27017
    # ?
    ports:
      - "27020:27017"
    # ?
    expose:
      - "27017"
    # ?
    volumes:
      - /etc/localtime:/etc/localtime:ro

volumes:
  volume: