version: "3.9"
services:
  # ReplicaSet1 Node 1
  mongoRS1n1:
    image: mongo
    container_name: mongoRS1n1
    # Terminal emulator: xterm
    environment:
      - TERM=xterm
    # ?
    ports:
      - "27017:27017"
    # ?
    expose:
      - "27017"
    # ?
    command: mongod --shardsvr --replSet mongoRS1 --dbpath /data/db --port 27017
    # ?
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./database/data1:/data/db

  # ReplicaSet1 Node 2
  mongoRS1n2:
    image: mongo
    container_name: mongoRS1n2
    # Terminal emulator: xterm
    environment:
      - TERM=xterm
    # ?
    ports:
      - "27027:27017"
    # ?
    expose:
      - "27017"
    # ?
    command: mongod --shardsvr --replSet mongoRS1 --dbpath /data/db --port 27017
    # ?
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./database/data2:/data/db

  # ReplicaSet1 Node 3
  mongoRS1n3:
    image: mongo
    container_name: mongoRS1n3
    # Terminal emulator: xterm
    environment:
      - TERM=xterm
    # ?
    ports:
      - "27037:27017"
    # ?
    expose:
      - "27017"
    # ?
    command: mongod --shardsvr --replSet mongoRS1 --dbpath /data/db --port 27017
    # ?
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./database/data3:/data/db

  # ReplicaSet2 Node 1
  mongoRS2n1:
    image: mongo
    container_name: mongoRS2n1
    # Terminal emulator: xterm
    environment:
      - TERM=xterm
    # ?
    ports:
      - "27047:27017"
    # ?
    expose:
      - "27017"
    # ?
    command: mongod --shardsvr --replSet mongoRS2 --dbpath /data/db --port 27017
    # ?
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./database/data4:/data/db

  # ReplicaSet2 Node 2
  mongoRS2n2:
    image: mongo
    container_name: mongoRS2n2
    # Terminal emulator: xterm
    environment:
      - TERM=xterm
    # ?
    ports:
      - "27057:27017"
    # ?
    expose:
      - "27017"
    # ?
    command: mongod --shardsvr --replSet mongoRS2 --dbpath /data/db --port 27017
    # ?
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./database/data5:/data/db

  # ReplicaSet2 Node 3
  mongoRS2n3:
    image: mongo
    container_name: mongoRS2n3
    # Terminal emulator: xterm
    environment:
      - TERM=xterm
    # ?
    ports:
      - "27067:27017"
    # ?
    expose:
      - "27017"
    # ?
    command: mongod --shardsvr --replSet mongoRS2 --dbpath /data/db --port 27017
    # ?
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./database/data6:/data/db

  # Config Server 1
  mongoCFG1:
    image: mongo
    container_name: mongoCFG1
    # Terminal emulator: xterm
    environment:
      - TERM=xterm
    # ?
    expose:
      - "27017"
    # ?
    command: mongod --configsvr --replSet configServerRS --dbpath /data/db --port 27017
    # ?
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./mongo_cluster/config1:/data/db

  # Config Server 2
  mongoCFG2:
    image: mongo
    container_name: mongoCFG2
    # Terminal emulator: xterm
    environment:
      - TERM=xterm
    # ?
    expose:
      - "27017"
    # ?
    command: mongod --configsvr --replSet configServerRS --dbpath /data/db --port 27017
    # ?
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./mongo_cluster/config2:/data/db

  # Config Server 3
  mongoCFG3:
    image: mongo
    container_name: mongoCFG3
    # Terminal emulator: xterm
    environment:
      - TERM=xterm
    # ?
    expose:
      - "27017"
    # ?
    command: mongod --configsvr --replSet configServerRS --dbpath /data/db --port 27017
    # ?
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./mongo_cluster/config3:/data/db

  # Router Instance
  router:
    image: mongo
    container_name: router
    # ?
    depends_on: 
      - mongoCFG1
      - mongoCFG2
    # ?
    command: mongos --configdb configServerRS/mongoCFG1:27017,mongoCFG2:27017,mongoCFG3:27017 --port 27017
    # ?
    ports:
      - "27019:27017"
    # ?
    expose:
      - "27017"
    # ?
    volumes:
      - /etc/localtime:/etc/localtime:ro

  # Router Instance 2
  #router2:
    #image: mongo
    #container_name: router2
    # ?
    #depends_on: 
      #- mongoCFG1
      #- mongoCFG2
    # ?
    #command: mongos --configdb configServerRS/mongoCFG1:27017,mongoCFG2:27017,mongoCFG3:27017 --port 27017
    # ?
    #ports:
      #- "27020:27017"
    # ?
    #expose:
      #- "27017"
    # ?
    #volumes:
      #- /etc/localtime:/etc/localtime:ro

volumes:
  volume: